### ISSUE TITLE
Wkhtmltopdf was not found on this system. The report will be displayed in HTML.

### ISSUE THREAD

**Issue by Tofdu31** [bitnami/bitnami-docker-odoo#47] opened 2018-06-28 07:43 UTC
Hi all,

I have a problem for several days.
After creating an invoice, I do not have the possibility to have it in pdf format and I have the following message: "Wkhtmltopdf was not found on this system.The report will be displayed in HTML."

I have version 11 of Odoo.
My server is: Debian 9.4
To manage my containers, I use Portainer.io
When I open a console, and I'm the procedure here:

```
wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
tar -xvf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz 
sudo cp ./wkhtmltox/bin/wkhtmltoimage /usr/bin/
sudo cp ./wkhtmltox/bin/wkhtmltopdf /usr/bin/
sudo sudo /opt/bitnami/ctlscript.sh restart
```
I have an error message telling me that wget is not installed.

Unfortunately when I type
apt-get install wget

I have the following error message:
```
root@b0a8d46a1121:/# apt-get install wget
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package wget
```
Thanks for your help
Christophe

**Comment by marcosbc** [comment] 2018-06-28 13:38
Hi,

By default, our containers come with an empty list of known packages from remote package repositories. You can regenerate this list by running the command below:

```bash
sudo apt-get update
```

After this, you'll be able to install wget with the command you were trying.

Apart from that, note that Bitnami containers don't contain "/opt/bitnami/ctlscript.sh", so in order to restart the Odoo service, you will need to restart the container.

In your case, you would run the following command:

```
docker restart name-of-your-container
```

**Comment by Tofdu31** [comment] 2018-06-28 15:43
Hi marcosbc,

Many thank for your help !

This is the procedure :
- 1 - 
`sudo apt-get update`
- 2 -
`sudo apt-get install wget`
- 3 - 
`sudo apt-get install tar`
- 4 -
`sudo apt-get install xz-utils`
- 5 -
Go to the tmp folder
`cd tmp`
- 6 -
`wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz`
- 7 - 
`tar -xvf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz`
- 8 -
`sudo cp ./wkhtmltox/bin/wkhtmltoimage /usr/bin/`
- 9 -
`sudo cp ./wkhtmltox/bin/wkhtmltopdf /usr/bin/`
- 10 - 
Restart the container !

I created the procedure because it will certainly serve other people.

Thank you again for your help

Tof

**Comment by Tofdu31** [comment] 2018-06-28 16:30
Aieee,
I still have the error message: Wkhtmltopdf was not found on this system. The report will be displayed in HTML.

**Comment by marcosbc** [comment] 2018-06-29 12:22
Hi,

We have been able to reproduce your issue. After checking the Odoo source, it seems to be unable to locate the binary (which is at `/usr/bin`), meaning that the PATH is wrong when running Odoo.

We've opened an internal task for fixing this issue. Unfortunately we're unable to give you an estimation of then this will be fixed, but we'll keep you in the loop with any update.

In the meantime, if you want to fix this by yourself, you can change the function `_get_wkhtmltopdf_bin()` in `/opt/bitnami/odoo/odoo/addons/base/ir/ir_actions_report.py` to return the fixed path to the binary. For instance:

```
sed -i "s:find_in_path..wkhtmltopdf.*$:'/usr/bin/wkhtmltopdf':" /opt/bitnami/odoo/odoo/addons/base/ir/ir_actions_report.py
```

This is not the ideal solution, but will work for you.

**Comment by Tofdu31** [comment] 2018-06-29 13:10
Hello Marco,

Thank you for your reply. Indeed, I will have to activate the mode developer and indicate the key with his path.

Then I will not have to restart the Odoo container but restart my Debian server completely for it to work.

I hope it can help you to solve your ticket

It's a pleasure to help you

Christophe
  37 bis rue du Général de Gaulle
31600 SEYSSES    Laborde Christophe
Consultant MDM / Mobility Manager
Chargé de projet
Expert WSO2 EMM / WSO2 IoT
Expert technique Android 
  +33 6 28 06 41 86 (tel:+33%206%2028%2006%2041%2086)  
  (#christophe.laborde@nbility.fr) christophe.laborde@nbility.fr (mailto:christophe.laborde@nbility)  
  Cliquer ici (https://www.linkedin.com/in/christophe-laborde-778074134)    (#www.nbility.fr) www.nbility.fr (http://www.nbility.fr)   
29 juin 2018 14:22 "Marcos Bjoerkelund" <notifications@github.com (mailto:notifications@github.com?to=%22Marcos%20Bjoerkelund%22%20<notifications@github.com>)> a écrit:
	Hi, 

	We have been able to reproduce your issue. After checking the Odoo source, it seems to be unable to locate the binary (which is at /usr/bin), meaning that the PATH is wrong when running Odoo. 

	We've opened an internal task for fixing this issue. Unfortunately we're unable to give you an estimation of then this will be fixed, but we'll keep you in the loop with any update. 

	In the meantime, if you want to fix this by yourself, you can change the function _get_wkhtmltopdf_bin() in /opt/bitnami/odoo/odoo/addons/base/ir/ir_actions_report.py to return the fixed path to the binary. For instance: 

	sed -i "s:find_in_path..wkhtmltopdf.*$:'/usr/bin/wkhtmltopdf':" /opt/bitnami/odoo/odoo/addons/base/ir/ir_actions_report.py  

	This is not the ideal solution, but will work for you.

**Comment by marcosbc** [comment] 2018-07-18 14:58
Hi,

Just wanted to let you know that we released a new revision of the Bitnami Odoo container, which includes a fix for the PATH issue.

Now, it will be enough to install wkhtmltopdf during container build time, in order to have it working in your Odoo site.

Please let us know if it works for you. Don't forget to pull again the new Bitnami Odoo Docker image.

**Comment by HarlekinSimplex** [comment] 2018-07-19 06:41
Hi,
Sounds good!
But what do you mean with install wkhtmltopdf during container build time?
How is that achieved?
By now I call a custom script to install it by using a custom entry point in the docker-compose.yml and a bash script... 

-----Original Message-----

**Comment by marcosbc** [comment] 2018-07-19 07:32
Hi,

If that works for you, it should be enough. Note that you can also do so by creating a new Docker image:

- Create the following `Dockerfile`:

```
FROM bitnami/odoo:latest

RUN WKHTMLVERSION=0.12.4 && \
    install_packages xz-utils zlib1g fontconfig libxrender1 libfreetype6 libxext6 libx11-6 && \
    cd /tmp && \
    curl -L https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/$WKHTMLVERSION/wkhtmltox-${WKHTMLVERSION}_linux-generic-amd64.tar.xz | tar xJ && \
    cp ./wkhtmltox/bin/wkhtmltoimage /usr/bin && \
    cp ./wkhtmltox/bin/wkhtmltopdf /usr/bin && \
    rm -rf wkhtmltox*
```

- Build the new Docker image (e.g. tagged as `myodoo`):

```
docker build -t myodoo .
```
- Update your `docker-compose.yml`:

```
    image: 'myodoo'
```

**Comment by marcosbc** [comment] 2018-10-29 13:10
@Tofdu31 It seems you did not follow all our instructions. Note that you need to install a set of dependencies, especially those related to rendering and fonts:

    install_packages xz-utils zlib1g fontconfig libxrender1 libfreetype6 libxext6 libx11-6

If you don't, you will see a message like this after restarting the Odoo container:

    odoo_1        | 2018-10-29 13:07:37,887 31 INFO bitnami_odoo odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf
    odoo_1        | 2018-10-29 13:07:37,888 31 INFO bitnami_odoo odoo.addons.base.ir.ir_actions_report: Wkhtmltopdf seems to be broken.

And when you run "/usr/bin/wkhtmltopdf" you will get this error:

    $ /usr/bin/wkhtmltopdf --version
    /usr/bin/wkhtmltopdf: error while loading shared libraries: libXrender.so.1: cannot open shared object file: No such file or directory

Were you able to get it to work after following the instructions again? Note the steps mentioned here: https://github.com/bitnami/bitnami-docker-odoo/issues/47#issuecomment-406182904.

**Comment by Tofdu31** [comment] 2018-10-29 13:20
Yes it's perfect, but I must admit that I galley a little.

You planned when the fix in the image Bitnami / odoo?

**Comment by marcosbc** [comment] 2018-10-30 08:33
The issue we mentioned above was related to Odoo not having a proper PATH during start, so it would not find wkhtmltopdf in /usr/bin (or /usr/local/bin). This was already fixed.

There are no pending issues to be fixed related to this.
If you mean when we plan to include wkhtmltopdf, we don't since its dependencies take a huge amount of space (up to 50M), which for a container is a lot.
Instead, we have documented how to install it in our docs, and we might also add it in the GitHub readme.

**Comment by Tofdu31** [comment] 2018-10-30 10:02
Ok thanks for your reply

**Comment by marcosbc** [comment] 2018-10-30 11:49
You're welcome! Since it seems this issue has been resolved, I'll close this case. Feel free to re-open if you find any related issue.

**Closed by marcosbc** 2018-10-30 11:49 UTC
